sonlar = list(map(int, input().split()))
jami_count = len(sonlar)
jami_sum = sum(sonlar)
eng_kichik = min(sonlar)
eng_katta = max(sonlar)
o_rtacha = jami_sum / jami_count
juftlar = sum(1 for x in sonlar if x % 2 == 0)
toqlar = sum(1 for x in sonlar if x % 2 != 0)
print(f"count: {jami_count}")
print(f"sum: {jami_sum}")
print(f"min: {eng_kichik}")
print(f"max: {eng_katta}")
print(f"mean: {o_rtacha:.2f}")
print(f"evens: {juftlar}")
print(f"odds: {toqlar}")